name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          # Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
          # The default is to check ALL files that were changed in in the pull_request or push.
          # Note: `ignorePaths` defined in cspell.json still apply.
          # Example:
          # files: |
          #   **/*.{ts,js}
          #   !dist/**/*.{ts,js}
          #
          # Default: ALL files
          files: ''

          # Check files and directories starting with `.`.
          # - "true" - glob searches will match against `.dot` files.
          # - "false" - `.dot` files will NOT be checked.
          # - "explicit" - glob patterns can match explicit `.dot` patterns.
          check_dot_files: explicit

          # The point in the directory tree to start spell checking.
          # Default: .
          root: '.'

          # Notification level to use with inline reporting of spelling errors.
          # Allowed values are: warning, error, none
          # Default: warning
          inline: warning

          # Determines if the action should be failed if any spelling issues are found.
          # Allowed values are: true, false
          # Default: true
          strict: true

          # Limit the files checked to the ones in the pull request or push.
          incremental_files_only: true

          # Path to `cspell.json`
          config: '.'

          # Log progress and other information during the action execution.
          # Default: false
          verbose: false

          # Use the `files` setting found in the CSpell configuration instead of `input.files`.
          use_cspell_files: false
